# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
name: Doctor Octopus Tests
run-name: DO ${{ inputs.test_suite }} Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:
    inputs:
      test_suite:
        description: "Test suite to run"
        required: true
        default: "smoke"
        type: choice
        options:
          - Smoke
          - Sanity
          - Regression
  workflow_call:
    inputs:
      test_suite:
        description: "Test suite to run"
        required: true
        type: string
        default: "regression"
jobs:
  build:
    name: ${{ inputs.test_suite }} Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [23.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Create test reports directory
        run: mkdir -p test_reports
      - name: Create CI info file
        run: |
          cat > test_reports/ci-info.json << 'EOF'
          {
            "run-id": "${{ github.run_id }}",
            "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          }
          EOF
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - name: Install Playwright Dependencies
        run: |
          cd playwright
          npm ci
          npx playwright install
      - name: Run Playwright Tests
        env:
          AWS_SDET_BUCKET_NAME: ${{ secrets.AWS_SDET_BUCKET_NAME }}
          AWS_SDET_BUCKET_REGION: ${{ secrets.AWS_SDET_BUCKET_REGION }}
          AWS_SDET_BUCKET_ACCESS_KEY_ID: ${{ secrets.AWS_SDET_BUCKET_ACCESS_KEY_ID }}
          AWS_SDET_BUCKET_SECRET_ACCESS_KEY: ${{ secrets.AWS_SDET_BUCKET_SECRET_ACCESS_KEY }}
        run: |
          pwd
          cd playwright
          if [[ "${{ inputs.test_suite }}" == "Smoke" ]]; then
            ENVIRONMENT=qa APP=clo npm run api:smoke
          elif [[ "${{ inputs.test_suite }}" == "Sanity" ]]; then
            ENVIRONMENT=qa APP=loan npm run api:sanity
          elif [[ "${{ inputs.test_suite }}" == "Regression" ]]; then
            ENVIRONMENT=qa APP=loan npm run ui:regression
          else
            ENVIRONMENT=qa APP=loan npm run s3:smoke  # Default to smoke tests
          fi
      - name: Upload CI info artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: ci-info
          path: test_reports/ci-info.json
